name: CI with nextjs

on:
  push: 
    branches: [main]
  pull_request:
    branched: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code to ubuntu server of github
        uses: actions/checkout@v3

      - name: Setup nodejs of ubuntu-latest
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test-storybook -- --coverage

      - name: Upload coverage result to ubuntu server of github
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Check coverage
        id: coverage
        run: |
          COVERAGE=$(grep -Po '(?<=\bline\s+).*?(?=%)' coverage/coverage-summary.json)
          echo "Coverage: $COVERAGE"
          if [ "$COVERAGE" -lt 50 ]; then
            echo "Coverage is less than 50%. Failing build."
            exit 1
          fi